#define LEFT_FRONT_PORT 4, true
#define LEFT_MIDDLE_PORT 13, false
#define LEFT_BACK_PORT 14, true
#define RIGHT_FRONT_PORT 12, false
#define RIGHT_MIDDLE_PORT 2, true
#define RIGHT_BACK_PORT 1, false
#define FRONT_LIFT_PORT 10, true
#define TRANSMISSION_PORT 3, true

#define FRONT_CLAW_PORT 4, false
#define BACK_CLAW_PORT 0, false
#define TILTER_PORT 8, false
#define SHIFTER_PORT 7, false

#define TRANSMISSION_BUTTON_PORT 3

#define FRONT_FOUR_BAR_ROTATION_PORT 19, false
#define BACK_FOUR_BAR_ROTATION_PORT 9, false
#define ROLLERS_ROTATION_PORT 6, true

#define LEFT_FRONT_FOUR_BAR_DISTANCE_PORT 18
#define RIGHT_FRONT_FOUR_BAR_DISTANCE_PORT 15
#define LEFT_BACK_FOUR_BAR_DISTANCE_PORT 5
#define RIGHT_BACK_FOUR_BAR_DISTANCE_PORT 8
#define LEFT_TRACKING_RESET_PORT 7
#define RIGHT_TRACKING_RESET_PORT 17
#define FRONT_LEFT_TRACKING_RESET_PORT 21
#define FRONT_RIGHT_TRACKING_RESET_PORT 11

#define Y_TRACKING_WHEEL_PORT 1, false
#define X_TRACKING_WHEEL_PORT 5, false
#define INERTIAL_PORT 16
