#define LEFT_FRONT_PORT 2, false
#define LEFT_MIDDLE_PORT 1, true
#define LEFT_BACK_PORT 12, true
#define RIGHT_FRONT_PORT 8, true
#define RIGHT_MIDDLE_PORT 10, false
#define RIGHT_BACK_PORT 20, false
#define FOUR_BAR_PORT 5, false
#define ROLLER_PORT 16, true

#define FRONT_CLAW_PORT 6, true
#define TWO_BAR_PORT 5, true

#define SELECTOR_PORT 8

#define FOUR_BAR_ROTATION_PORT 14, true

#define FOUR_BAR_DISTANCE_PORT 6
#define LEFT_FOUR_BAR_ALIGNER_DISTANCE_PORT 3
#define RIGHT_FOUR_BAR_ALIGNER_DISTANCE_PORT 9
#define TWO_BAR_DISTANCE_PORT 11
#define LEFT_TWO_BAR_ALIGNER_DISTANCE_PORT 4
#define RIGHT_TWO_BAR_ALIGNER_DISTANCE_PORT  17

#define LEFT_TRACKING_RESET_PORT 13
#define RIGHT_TRACKING_RESET_PORT 19
#define FRONT_LEFT_TRACKING_RESET_PORT 3
#define FRONT_RIGHT_TRACKING_RESET_PORT 9
#define BACK_LEFT_TRACKING_RESET_PORT 4
#define BACK_RIGHT_TRACKING_RESET_PORT 17

#define Y_TRACKING_WHEEL_PORT 3, true
#define X_TRACKING_WHEEL_PORT 1, false
#define INERTIAL_PORT 18
