#include "robot.hpp"

Motor leftBaseMotors[3] = {Motor(LEFT_FRONT_PORT), Motor(LEFT_MIDDLE_PORT), Motor(LEFT_BACK_PORT)};
Motor rightBaseMotors[3] = {Motor(RIGHT_FRONT_PORT), Motor(RIGHT_MIDDLE_PORT), Motor(RIGHT_BACK_PORT)};
Base base(leftBaseMotors, rightBaseMotors);
FourBar fourBar(Motor(FOUR_BAR_PORT), Claw(Piston(FRONT_CLAW_PORT), Distance(FOUR_BAR_DISTANCE_PORT), Distance(LEFT_FOUR_BAR_ALIGNER_DISTANCE_PORT), Distance(RIGHT_FOUR_BAR_ALIGNER_DISTANCE_PORT), BACK_CLAW_ALIGNER_LOCAL_Y_OFFSET, FRONT_CLAW_GRAB_DISTANCE), Rotation(FOUR_BAR_ROTATION_PORT));
Claw twoBar(Piston(TWO_BAR_PORT), Distance(TWO_BAR_DISTANCE_PORT), Distance(LEFT_TWO_BAR_ALIGNER_DISTANCE_PORT), Distance(RIGHT_TWO_BAR_ALIGNER_DISTANCE_PORT), BACK_CLAW_ALIGNER_LOCAL_Y_OFFSET, BACK_CLAW_GRAB_DISTANCE);
Rollers rollers(Motor(ROLLER_PORT));
Auton auton;
DriveControl driveControl;
Odometry odom(TrackingWheel(X_TRACKING_WHEEL_PORT, X_TRACKING_WHEEL_DISTANCE, 2.75), TrackingWheel(Y_TRACKING_WHEEL_PORT, Y_TRACKING_WHEEL_DISTANCE, 2.75), Inertial(INERTIAL_PORT), Distance(LEFT_TRACKING_RESET_PORT), Distance(RIGHT_TRACKING_RESET_PORT), Distance(FRONT_LEFT_TRACKING_RESET_PORT), Distance(FRONT_RIGHT_TRACKING_RESET_PORT), Distance(BACK_LEFT_TRACKING_RESET_PORT), Distance(BACK_RIGHT_TRACKING_RESET_PORT));
Controller controller;
